"""add telegram_chat_id and bot_token to users

Revision ID: 202faf9a34e1
Revises: b8c6a6c30006
Create Date: 2026-06-24 11:37:16.366818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202faf9a34e1'
down_revision: Union[str, Sequence[str], None] = 'b8c6a6c30006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bot_token', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_column('users', 'bot_token')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
