"""add category to receipt_item

Revision ID: b93f443f4a29
Revises: a7e3f91b2c40
Create Date: 2026-06-14 22:04:45.477194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93f443f4a29'
down_revision: Union[str, Sequence[str], None] = 'a7e3f91b2c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_items', 'category')
    # ### end Alembic commands ###
